output:
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
  wsl:
    allow-assign-and-anything: false
  exhaustruct:
    exclude:
      - 'cobra\.Command$'
      - '.*'
  varnamelen:
    min-name-length: 1
  depguard:
    rules:
      main:
        # List of allowed packages.
        allow:
          - $gostd
          - github.com/OpenPeeDeeP
          - github.com/spf13/viper
          - battle-of-monsters/
          - github.com/gin-gonic/gin
          - github.com/golang-migrate/migrate/v4
          - github.com/golang-migrate/migrate/v4/
          - github.com/spf13/cobra
          - modernc.org/sqlite
          - github.com/onsi/ginkgo/v2
          - github.com/onsi/gomega
          - github.com/go-playground/validator/v10
  revive:
    rules:
      - name: dot-imports
        severity: warning
        disabled: true
  goimports:
    local-prefixes: github.com/org/project
  

issues:
  exclude-rules:
    - path: migrations/...
      linters:
        - gochecknoinits
        - forbidigo
        - wrapcheck
    - path: app/models/...
      linters:
        - nestif
    - path: cmd
      linters:
        - forbidigo
        - gochecknoglobals
        - gochecknoinits
    - source: "DB|CONN|ENV|migrations"
      linters:
        - gochecknoglobals
    - text: TODO
      linters:
        - godox
  
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gci
    - paralleltest
    - gofumpt

    # deprecated
    - interfacer
    - scopelint
    - maligned
